#+begin_src python :results drawer :exports results
import export
return export.make_parser().prog
#+end_src

#+RESULTS:
:results:
Export your Github personal data: issues, PRs, comments, followers and followings, etc.

*Note*: this only deals with metadata. If you want a download of actual git repositories, I recommend using [[https://github.com/josegonzalez/python-github-backup][python-github-backup]].
:end:

* Setting up
1. =pip3 install --user -r requirements.txt=
2. To use the API, you need to register a [[https://github.com/settings/tokens][get a =token=]] from settings.
 
* Exporting

#+begin_src python :results drawer :exports results 
import export; return export.make_parser().epilog
#+end_src

#+RESULTS:
:results:

Usage:

*Recommended*: create =secrets.py= keeping your api parameters, e.g.:


: token = "TOKEN"


After that, use:

: ./export.py --secrets /path/to/secrets.py

That way you type less and have control over where you keep your plaintext secrets.

*Alternatively*, you can pass parameters directly, e.g.

: ./export.py --token <token>

However, this is verbose and prone to leaking your keys/tokens/passwords in shell history.

    
You can also import ~export.py~ as a module and call ~get_json~ function directly to get raw JSON.
        

I *highly* recommend checking exported files at least once just to make sure they contain everything you expect from your export. If not, please feel free to ask or raise an issue!
    
:end:

* API limitations

*WARNING*: github API limits extent to which you can retrieve certain data, e.g. [[https://developer.github.com/v3/activity/events][events]] you can only get events from the past 90 days, and not more than 300 events.

I *highly* recommend to export regularly and keep old exports. Easy way to achieve it is command like this: 

: ./export.py --secrets /path/to/secrets.py >"export-$(date -I).json"

Or, you can use [[https://github.com/karlicoss/arctee][arctee]] that automates this.


To get your older data past 90 days, you can request a [[https://github.com/settings/admin][manual export]] in your account settings.

# TODO hmm, mention that dal.py can handle this?

* Using data
  
#+begin_src python :results drawer :exports results 
import dal_helper; return dal_helper.make_parser().epilog
#+end_src

#+RESULTS:
:results:

You can use =dal.py= (stands for "Data Access/Abstraction Layer") to access your exported data, even offline.
I elaborate on motivation behind it [[https://beepb00p.xyz/exports.html#dal][here]].

- main usecase is to be imported as python module to allow for *programmatic access* to your data.

  You can find some inspiration in [[https://beepb00p.xyz/mypkg.html][=my.=]] package that I'm using as an API to all my personal data.

- to test it against your export, simply run: ~./dal.py --source /path/to/export~

- you can also try it interactively: ~./dal.py --source /path/to/export --interactive~

:end:

Example output:

: Your events:
: Counter({'PushEvent': 181,
:          'WatchEvent': 27,
:          'CreateEvent': 22,
:          'IssueCommentEvent': 20,
:          'PullRequestEvent': 15,
:          'IssuesEvent': 5,
:          'DeleteEvent': 5,
:          'ForkEvent': 3,
:          'PullRequestReviewCommentEvent': 1})


